config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  root 'categories#index'

  post 'items/:id/add_to_cart', to: "items#add_to_cart"
  # resources :carts, only: [:index, :create, :edit, :update, :destroy]
  resources :categories, only: [:index, :show] do
    collection do
      post :search
      get :autocomplete
    end
  end
  resources :items, only: [:index, :show, :update]
  resources :comments, only: [:create, :index, :show, :new]

  # post 'categories/search', to: 'categories#search'
  get 'carts/index'
  post 'carts/create'
  patch 'carts/update'
  get 'carts/destroy'
  
  resources :orders, only: [:index, :show, :create, :new, :destroy]
  resources :ratings, only: [:update]
  namespace :admin do
  	root 'categories#index'

  	resources :categories do
    	resources :items
      collection do
        post :search
        get :autocomplete
      end
    end
  end
end

app/views/shared/_footer.html.erb
<footer id="footer"><!--Footer-->
	<div class="footer-widget">
		<div class="container">
			<div class="row">
				<div class="col-sm-2">
					<div class="single-widget">
						<h2>Service</h2>
						<ul class="nav nav-pills nav-stacked">
							<li><a href="#">Online Help</a></li>
							<li><a href="#">Contact Us</a></li>
							<li><a href="#">Order Status</a></li>
							<li><a href="#">Change Location</a></li>
							<li><a href="#">FAQ’s</a></li>
						</ul>
					</div>
				</div>
				<div class="col-sm-2">
					<div class="single-widget">
						<h2>Quock Shop</h2>
						<ul class="nav nav-pills nav-stacked">
							<li><a href="#">T-Shirt</a></li>
							<li><a href="#">Mens</a></li>
							<li><a href="#">Womens</a></li>
							<li><a href="#">Gift Cards</a></li>
							<li><a href="#">Shoes</a></li>
						</ul>
					</div>
				</div>
				<div class="col-sm-2">
					<div class="single-widget">
						<h2>Policies</h2>
						<ul class="nav nav-pills nav-stacked">
							<li><a href="#">Terms of Use</a></li>
							<li><a href="#">Privecy Policy</a></li>
							<li><a href="#">Refund Policy</a></li>
							<li><a href="#">Billing System</a></li>
							<li><a href="#">Ticket System</a></li>
						</ul>
					</div>
				</div>
				<div class="col-sm-2">
					<div class="single-widget">
						<h2>About Shopper</h2>
						<ul class="nav nav-pills nav-stacked">
							<li><a href="#">Company Information</a></li>
							<li><a href="#">Careers</a></li>
							<li><a href="#">Store Location</a></li>
							<li><a href="#">Affillate Program</a></li>
							<li><a href="#">Copyright</a></li>
						</ul>
					</div>
				</div>
				<div class="col-sm-3 col-sm-offset-1">
					<div class="single-widget">
						<h2>About Shopper</h2>
						<form action="#" class="searchform">
							<input type="text" placeholder="Your email address" />
							<button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
							<p>Get the most recent updates from <br />our site and be updated your self...</p>
						</form>
					</div>
				</div>
				
			</div>
		</div>
	</div>
	
	<div class="footer-bottom">
		<div class="container">
			<div class="row">
				<p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
				<p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
			</div>
		</div>
	</div>
	
</footer><!--/Footer-->

app/views/shared/_header.html.erb
	<header id="header"><!--header-->
		<div class="header_top"><!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								<li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
								<li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<ul class="nav navbar-nav">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->
		
		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
							<a href=<%= root_path %>><img src="http://res.cloudinary.com/dfg9corup/image/upload/v1494961946/logo_ksct52.png" alt="" /></a>
						</div>
						<div class="btn-group pull-right">					
						</div>
					</div>
					<div class="col-sm-8">
						<div class="shop-menu pull-right">
							<ul class="nav navbar-nav">
								<% if user_signed_in? %>
                  <li><div><a href=<%= carts_index_path %>><i class="fa fa-shopping-cart"></i> Cart</a></div></li>
                  <li><div><%= link_to "<i class='fa fa-sign-out' aria-hidden='true'></i>Logout".html_safe, destroy_user_session_path, method: :delete %></div></li>
                  <% if current_user.admin? %>
                    <li><div class="admin_category"><%= link_to "<i class='fa fa-user' aria-hidden='true'></i>Admin".html_safe, admin_root_path %></div></li>
                  <% end %>
                <% else %>
                  <li><div><%= link_to "<i class='fa fa-sign-out' aria-hidden='true'></i><b>Login/Register</b>".html_safe, new_user_session_path %></div></li>
                  <li class="dropdown">
			              <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="margin-top: 0px;"><b>Others</b> <span class="caret"></span></a>
			              <ul id="login-dp" class="dropdown-menu">
			                <li>
			                  <div class="row">
			                    <div class="col-md-12">
			                      Login via
			                      <div class="social-buttons">
			                        <a href="/users/auth/facebook" class="btn btn-fb"><i class="fa fa-facebook"></i> Facebook</a>
			                        <a href="#" class="btn btn-tw"><i class="fa fa-twitter"></i> Twitter</a>
			                      </div>
			                    </div>
			                  </div>
			                </li>
			              </ul>
			            </li>
                <% end %>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->
	
		<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
							<div class="container">
								<div class="col-sm-3 pull-right">
									<div class="search_box">
										<%= form_tag search_categories_path do %>
								       <input type="text" name="query" id="item_search" class="item_search" placeholder="Enter item name" autocomplete="off" >
								       <button class="btn btn-primary" style="margin-top: 12px;">Search</button>
								     <% end %>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->