config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  root 'categories#index'

  post 'items/:id/add_to_cart', to: "items#add_to_cart"
  # resources :carts, only: [:index, :create, :edit, :update, :destroy]
  resources :categories, only: [:index, :show] do
    collection do
      post :search
      get :autocomplete
    end
  end
  resources :items, only: [:index, :show, :update]
  resources :comments, only: [:create, :index, :show, :new]

  # post 'categories/search', to: 'categories#search'
  get 'carts/index'
  post 'carts/create'
  patch 'carts/update'
  get 'carts/destroy'
  
  resources :orders, only: [:index, :show, :create, :new, :destroy]
  resources :ratings, only: [:update]
  namespace :admin do
  	root 'categories#index'

  	resources :categories do
    	resources :items
      collection do
        post :search
        get :autocomplete
      end
    end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :item
  belongs_to :user

  validates :quantity, presence:true, numericality: {only_integer: true, greater_than: 0}
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  layout 'admin'
  
  before_action :authenticate_user!
  before_action :init, only: [:index, :create, :destroy]
  
  include CartHelper

  def index
    if current_user
      @cart_items = Item.where(:id => @item_id_array)
      show_total(@cart_items, @cart_quantity)
    end
  end
  def create
    session[:cart] << {'item_id' => params[:item_id], 'quantity' => 1} unless
                                                              @item_id_array.include?(params[:item_id])
  end

  def update
    update_cart(session[:cart])
  end


  def destroy
    @item_id_array.each_with_index do |item_id, index|
      if item_id == params[:item_id]
        session[:cart].delete_at(index)
      end
    end 
    redirect_to carts_index_path
  end

  def init
    session[:cart] ||= []
    cart_init(session[:cart])
  end

  private
  def carts_params
    params.require(:cart).permit(:quantity, :item_id)
  end

end

app/helpers/cart_helper.rb
module CartHelper
  NO = 0
  YES = 1

  def total_price(item, index)
    number_to_currency(item.price * @cart_quantity[index].to_i)
  end
  def show_total(cart_items, cart_quantity)
    @total = 0
    @number_item = 0
    @total_number_item = 0
    cart_items.each_with_index do |item, index|
      @total += item.price * cart_quantity[index].to_i
      @number_item += 1
      @total_number_item += cart_quantity[index].to_i
    end
  end

  def update_cart(session_cart_arr)
    check_contain = NO
    session_cart_arr ||= []
    session_cart_arr = session_cart_arr.sort_by! { |hash| hash['item_id']}
    session_cart_arr.each do |cart|
      if cart['item_id'] == params[:item_id]
        cart['quantity'] = params[:quantity].to_i
        check_contain = YES
      end
    end
    session_cart_arr << {'item_id' => params[:item_id], 'quantity' => params[:quantity].to_i} if
                                                                          check_contain == NO
    cart_init(session_cart_arr)

    @cart_items = Item.where(:id => @item_id_array)

    @item_id = params[:item_id]
    @total_price = params[:price].to_f * params[:quantity].to_i
    show_total(@cart_items, @cart_quantity)
  end

  def cart_init(session_cart_arr)
    @item_id_array = []
    @cart_quantity = []
    session_cart_arr = session_cart_arr.sort_by! { |hash| hash['item_id']}
    session_cart_arr.each do |cart|
      @item_id_array << cart['item_id']
      @cart_quantity << cart['quantity']
    end
  end
end

app/views/carts/index.html.erb
  <section id="cart_items">
    <div class="container">
      <div class="breadcrumbs">
        <ol class="breadcrumb">
          <li><%= link_to "Home", root_path %></li>
          <li class="active">Shopping Cart</li>
        </ol>
      </div>
      <div class="table-responsive cart_info">
        <table class="table table-condensed" style="width: 99%;">
          <thead>
            <tr class="cart_menu">
              <td class="image"><div class="text-center">Item</div></td>
              <td class="description"></td>
              <td class="price"><div class="text-center">Price</div></td>
              <td class="quantity"><div class="text-center">Quantity</div></td>
              <td class="total"><div class="text-center">Total</div></td>
            </tr>
          </thead>
          <% if current_user %>
            <tbody>
            <% @cart_items.each_with_index do |item, index| %>
              <tr id="tr_cart_<%= item.id%>">
                <td class="cart_product text-center">
                  <%= image_tag item.image.small_thumb.url %>
                </td>
                <td class="cart_description text-center">
                  <h4><%= link_to item.name, item_path(item.id) %></h4>
                </td>
                <td class="cart_price text-center">
                  <p ><%= number_to_currency(item.price) %></p>
                </td>
                <td class="cart_quantity text-center">
                  <div class="cart_quantity_button" style="display: inline;">
                    <%= form_for carts_index_path(:item_id => item.id, :quantity => @cart_quantity[index] ), :html => {:style => 'display: inline;', :id => 'edit_cart_' + "#{item.id}"} do |f| %>
                      <%= f.text_field :quantity, value: @cart_quantity[index], :style => 'width: 80px;', type: 'number', size: 2, :data_id => item.id, :data_price =>  item.price, class: 'cart_quantity', name: 'cart_quantity', id: 'quantity_input' %>
                      <%#= f.hidden_field :item_id, value: item.id %>
                    <% end %>
                  </div>
                </td>
                <td class="cart_total text-center">
                  <p class="cart_total_price" id="total_price_cart_<%=item.id%>"><%= total_price(item, index) %></p>
                </td>
                <td class="cart_delete">
                  <%= link_to '<i class="fa fa-times"></i>'.html_safe,carts_destroy_path(:item_id => item.id), class: 'cart_quantity_delete', :data_id => item.id, data: {confirm: 'Are you sure?'} %>
                </td>
              </tr>
            <% end %>
          </tbody>
          <tfoot>
            <tr class="cart_menu">
              <td class="image" id="total_item"><div class="text-center"><%= @number_item %> Items</div></td>
              <td class="description"></td>
              <td class="price"></td>
              <td class="quantity text-center" id="total_quantity">Total quantity <br/> <%= @total_number_item %></td>
              <td class="total text-center" id="total">Total<br/><%= number_to_currency(@total) %></td>
              <td></td>
            </tr>
          </tfoot>
          <% end %>
        </table>
        <div class="order_button">
          <%= link_to '<i class="fa fa-shopping-cart"></i> <b>ORDER</b>'.html_safe, new_order_path, class: 'btn btn-primary pull-right' %>
        </div>
      </div>
    </div>
  </section> <!--/#cart_items-->

app/views/carts/update.js.erb
$('#total_price_cart_<%=@item_id%>').html("<div style = 'text-align: center;'><%= number_to_currency(@total_price) %></div>")
$('#total_quantity').html("<div style = 'text-align: center;'>Total quantity<br/><%= @total_number_item %></div>");
$('#total_item').html("<div style = 'text-align: center;'><%= @number_item %> Items</div>");
$('#total').html("<div style = 'text-align: center;'>Total<br/><%= number_to_currency(@total) %></div>");