config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  root 'categories#index'

  post 'items/:id/add_to_cart', to: "items#add_to_cart"
  # resources :carts, only: [:index, :create, :edit, :update, :destroy]
  resources :categories, only: [:index, :show] do
    collection do
      post :search
      get :autocomplete
    end
  end
  resources :items, only: [:index, :show, :update]
  resources :comments, only: [:create, :index, :show, :new]

  # post 'categories/search', to: 'categories#search'
  get 'carts/index'
  post 'carts/create'
  patch 'carts/update'
  get 'carts/destroy'
  
  resources :orders, only: [:index, :show, :create, :new, :destroy]
  resources :ratings, only: [:update]
  namespace :admin do
  	root 'categories#index'

  	resources :categories do
    	resources :items
      collection do
        post :search
        get :autocomplete
      end
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin
  
  layout 'admin'
  
  def index
    @categories = Category.all
    @items = Item.includes(:category).all.order(:name)
    @orders = Order.all
  end

  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @item = @category.items.all.order(:name)
    @orders = Order.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category has been created successful"
      redirect_to admin_categories_path
    else
      flash.now[:error] = @category.errors.full_messages
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_path
  end

  def search
    @categories = Category.all
    @items = Item.search(params[:query], limit: 1)
    @orders = Order.all
    render :index
  end

  def autocomplete
    item_hash = Item.search(params[:query], match: :text_start,
                     limit: 5, load: false, misspellings: {below: 5}).map do |element|
      { name: element.name}
    end
    render json: item_hash
  end
  
  private
  def category_params
    params.require(:category).permit(:name)
  end
  def check_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]

  def index
    @categories = Category.all
    @items = Item.order(:name).paginate(page: params[:page], per_page: 9)
  end

  def show
    @categories = Category.all
  	@items = @category.items.paginate(page: params[:page], per_page: 6)
  end

  def search
    @categories = Category.all
    @items = Item.search(params[:query], limit: 1)
    render :index
  end

  def autocomplete
    item_hash = Item.all.map do |element|
      { name: element.name}
    end
    render json: item_hash
  end
  private

  def set_category
  	@category = Category.find_by_id params[:id]
  	redirect_to root_path unless @category.present?
  end

end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/admin/categories/_form.html.erb
<div class="col-md-offset-2">
  <%= form_for [:admin, @category] do |f| %>

      <% if flash[:error] %>
        <div class="text-danger">
          <% flash[:error].each do |msg| %>
            <p> <%= msg %> </p>
          <% end %>
        </div>
      <% end %>

      <div class="row col-md-8" style="margin: 50px 0;">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.submit class: 'btn btn-primary pull-right' %>
        </div>
      </div>

  <% end %>
</div>

app/views/admin/categories/edit.html.erb
<%= render 'form' %>

app/views/admin/categories/index.html.erb
  <div class="container-fluid">

    <div class="modal fade" id="myModal" role="dialog" style="padding: 30px;">

    </div>

    <div class="row">
      <div class="col-sm-4" style="clear: both; float: left;">
        <div class="left-sidebar">
          <h2>Category</h2>
          <div class="panel-group category-products"><!--category-productsr-->
            <%= link_to 'New Category', new_admin_category_path, class: 'btn btn-default' %>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 style="display: inline-block;">
                  <div class="admin_category_div" style="padding-right: 5px;">
                    <%= link_to "All", admin_categories_path, class: 'admin_category' %>
                  </div>
                </h4>
              </div>
              <% @categories.each do |category| %>
                <div class="panel-heading">
                  <h4 class="panel-title" style="display: inline-block;">
                  <div class="admin_category_div row" style="padding-right: 5px;">
                    <%= link_to category.name, admin_category_path(category.id), class: 'admin_category' %>
                  </div>
                  </h4>
                  <div class="navbar-right">
                    <div class="btn btn-default" style="padding: 0 2px;">
                    <%= link_to 'New Item', new_admin_category_item_path(category.id), remote: true %>
                  </div>
                  <div class="btn btn-default" style="padding: 0 2px;">
                    <%= link_to "Edit", edit_admin_category_path(category) %>
                  </div>
                  <div class="btn btn-default" style="padding: 0 2px;">
                    <%= link_to "Delete", admin_category_path(category.id), method: :delete, data: { confirm: 'Are you sure?' } %>
                  </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div><!--/category-products-->
            <%= link_to 'Order List', orders_path, class: 'btn btn-default' %>
            <hr>
            <div style="max-height: 200px; overflow: auto">
              <table class="table text-center">
              <thead>
                <tr>
                  <th class="text-center">ID</th>
                  <th class="text-center">Customer Name</th>
                  <th class="text-center">Address</th>
                </tr>
              </thead>

              <tbody>
                <% @orders.each do |order| %>
                  <tr>
                    <td><%= order.id  %></td>
                    <td><%= link_to order.customer_name, order_path(order.id) %></td>
                    <td><%= truncate(order.contact_address, length: 50, separator: ' ') %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            </div>
        </div>
      </div>
      
      <div class="col-sm-8" style="float: left; max-height: 550px; overflow: auto;">
        <div class="left-sidebar">
          <h2>Item</h2>
          <div class="container-fluid">
            <div class="col-sm-6 pull-right" style="position: fixed; top: 80px; left: 1000px;">
              <div class="search_box" >
                <%= form_tag search_admin_categories_path do %>
                   <input type="text" name="query" id="admin_item_search" class="item_search" placeholder="Enter item name" autocomplete="off" >
                   <button class="btn btn-primary">Search</button>
                 <% end %>
              </div>
            </div>
          </div>
          <div class="panel-group category-products"><!--category-productsr-->
            <div class="panel panel-default" id="admin_items">
              <table class="table">
                <thead>
                  <tr>
                    <th class="text-center">Image</th>
                    <th class="text-center">Name</th>
                    <th class="text-center">Price</th>
                    <th class="text-center">Actions</th>
                  </tr>
                </thead>

                <tbody class="text-center">
                  <% @items.each do |item| %>
                    <tr>
                      <td>
                        <%= image_tag item.image.small_thumb.url  %>
                      </td>
                      <td><%= link_to item.name, item_path(item.id) %></td>

                      <td><%= number_to_currency(item.price) %></td>
                      <td>
                        <%= link_to "<i class='fa fa-pencil-square-o fa-2x' aria-hidden='true'></i>".html_safe, edit_admin_category_item_path(item.category.id, item.id), remote: true %> --
                        <%= link_to "<i class='fa fa-trash-o fa-2x' aria-hidden='true'></i>".html_safe, admin_category_item_path(item.category.id, item.id), method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div><!--/category-products-->
        </div>
      </div>

    </div>
  </div>

  </div>

app/views/admin/categories/new.html.erb
<h2> New category </h2>
<%= render 'form' %>

app/views/admin/categories/show.html.erb
<div class="container-fluid">
  <% if flash[:notice] %>
      <div class="text-success">
        <%= flash[:notice] %>
      </div>
  <% end %>

  <div class="container-fluid">
  <div class="modal fade" id="myModal" role="dialog" style="padding: 30px;">
    </div>
    <div class="row">
      <div class="col-sm-4" style="clear: both; float: left;">
        <div class="left-sidebar">
          <h2>Category</h2>
          <div class="panel-group category-products"><!--category-productsr-->
            <%= link_to 'New Category', new_admin_category_path, class: 'btn btn-default' %>
            <div class="panel panel-default">
                <div class="panel-heading">
                  <h4 class="panel-title" style="display: inline-block;">
                    <div style="padding-right: 5px;">
                      <%= link_to "All", admin_categories_path, class: 'admin_category' %>
                    </div>
                  </h4>
                </div>
              <% @categories.each do |category| %>
                <div class="panel-heading">
                  <h4 class="panel-title" style="display: inline-block;">
                    <div style="padding-right: 5px;">
                      <%= link_to category.name, admin_category_path(category.id), class: 'admin_category' %>
                    </div>
                  </h4>
                  <div class="navbar-right">
                    <div class="btn btn-default" style="padding: 0 2px;">
                    <%= link_to 'New Item', new_admin_category_item_path(category.id), remote: true %>
                  </div>
                  <div class="btn btn-default" style="padding: 0 2px;">
                    <%= link_to "Edit", edit_admin_category_path(category) %>
                  </div>
                  <div class="btn btn-default" style="padding: 0 2px;">
                    <%= link_to "Delete", admin_category_path(category.id), method: :delete, data: { confirm: 'Are you sure?' } %>
                  </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div><!--/category-products-->
            <%= link_to 'Order List', orders_path, class: 'btn btn-default' %>
            <hr>
            <div style="max-height: 200px; overflow: auto">
              <table class="table table-hover text-center">
              <thead>
                <tr>
                  <th class="text-center">ID</th>
                  <th class="text-center">Customer Name</th>
                  <th class="text-center">Address</th>
                </tr>
              </thead>

              <tbody>
                <% @orders.each do |order| %>
                  <tr>
                    <td><%= order.id  %></td>
                    <td><%= link_to order.customer_name, order_path(order.id) %></td>
                    <td><%= truncate(order.contact_address, length: 50, separator: ' ') %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            </div>
        </div>
      </div>
      
      <div class="col-sm-8" style="float: left; max-height: 550px; overflow: auto;">
        <div class="left-sidebar">
          <h2>Item</h2>
          <div class="container-fluid">
            <div class="col-sm-6 pull-right" style="position: fixed; top: 80px; left: 1000px;">
              <div class="search_box" >
                <%= form_tag search_admin_categories_path do %>
                   <input type="text" name="query" id="admin_item_search" class="item_search" placeholder="Enter item name" autocomplete="off" >
                   <button class="btn btn-primary">Search</button>
                 <% end %>
              </div>
            </div>
          </div>
          <div class="panel-group category-products"><!--category-productsr-->
            <div class="panel panel-default" id="admin_items">
              <table class="table">
                <thead>
                  <tr>
                    <th class="text-center">Image</th>
                    <th class="text-center">Name</th>
                    <th class="text-center">Price</th>
                    <th class="text-center">Actions</th>
                  </tr>
                </thead>

                <tbody>
                  <% @item.each do |item| %>
                    <tr>
                      <td>
                        <%= image_tag item.image.small_thumb.url  %>
                      </td>
                      <td><%= link_to item.name, item_path(item.id) %></td>

                      <td><%= number_to_currency(item.price) %></td>
                      <td>
                        <%= link_to "<i class='fa fa-pencil-square-o fa-2x' aria-hidden='true'></i>".html_safe, edit_admin_category_item_path(item.category.id, item.id), remote: true %> --
                        <%= link_to "<i class='fa fa-trash-o fa-2x' aria-hidden='true'></i>".html_safe, admin_category_item_path(item.category.id, item.id), method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div><!--/category-products-->
        </div>
      </div>

    </div>
  </div>

  </div>

</div>