config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  root 'categories#index'

  post 'items/:id/add_to_cart', to: "items#add_to_cart"
  # resources :carts, only: [:index, :create, :edit, :update, :destroy]
  resources :categories, only: [:index, :show] do
    collection do
      post :search
      get :autocomplete
    end
  end
  resources :items, only: [:index, :show, :update]
  resources :comments, only: [:create, :index, :show, :new]

  # post 'categories/search', to: 'categories#search'
  get 'carts/index'
  post 'carts/create'
  patch 'carts/update'
  get 'carts/destroy'
  
  resources :orders, only: [:index, :show, :create, :new, :destroy]
  resources :ratings, only: [:update]
  namespace :admin do
  	root 'categories#index'

  	resources :categories do
    	resources :items
      collection do
        post :search
        get :autocomplete
      end
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin
  
  layout 'admin'
  
  def index
    @categories = Category.all
    @items = Item.includes(:category).all.order(:name)
    @orders = Order.all
  end

  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @item = @category.items.all.order(:name)
    @orders = Order.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category has been created successful"
      redirect_to admin_categories_path
    else
      flash.now[:error] = @category.errors.full_messages
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_path
  end

  def search
    @categories = Category.all
    @items = Item.search(params[:query], limit: 1)
    @orders = Order.all
    render :index
  end

  def autocomplete
    item_hash = Item.search(params[:query], match: :text_start,
                     limit: 5, load: false, misspellings: {below: 5}).map do |element|
      { name: element.name}
    end
    render json: item_hash
  end
  
  private
  def category_params
    params.require(:category).permit(:name)
  end
  def check_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]

  def index
    @categories = Category.all
    @items = Item.order(:name).paginate(page: params[:page], per_page: 9)
  end

  def show
    @categories = Category.all
  	@items = @category.items.paginate(page: params[:page], per_page: 6)
  end

  def search
    @categories = Category.all
    @items = Item.search(params[:query], limit: 1)
    render :index
  end

  def autocomplete
    item_hash = Item.all.map do |element|
      { name: element.name}
    end
    render json: item_hash
  end
  private

  def set_category
  	@category = Category.find_by_id params[:id]
  	redirect_to root_path unless @category.present?
  end

end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/_item_index.html.erb
<div>
  <% @items.each do |item| %>
    <div class="col-sm-4" style="height: 372px;" >
      <div class="product-image-wrapper">
        <div class="single-products">
          <div class="productinfo text-center">
            <%= link_to (image_tag item.image.thumb.url), item_path(item.id) %>
            <h2><%= number_to_currency(item.price) %></h2>
            <p><%= item.name %></p>
            <div class="btn btn-primary add-to-cart my_cart" id = 'add_to_cart_<%=item.id%>' style = 'margin-bottom: 15px; margin-top: 0' item-id = '<%= item.id%>' data-user = '<%= current_user %>' ><i class="fa fa-shopping-cart"></i>Add to cart</div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="col-md-6 col-md-offset-3">
    <%= will_paginate @items %>
  </div>
</div>

app/views/categories/index.html.erb
<section id="slider"><!--slider-->
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<div id="slider-carousel" class="carousel slide" data-ride="carousel">
					<ol class="carousel-indicators">
						<li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
						<li data-target="#slider-carousel" data-slide-to="1"></li>
						<li data-target="#slider-carousel" data-slide-to="2"></li>
					</ol>
					
					<div class="carousel-inner">
						<div class="item active">
							<div class="col-sm-6">
								<h1><span>E</span>-SHOPPER</h1>
								<h2>Free E-Commerce Template</h2>
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
								<button type="button" class="btn btn-default get">Get it now</button>
							</div>
							<div class="col-sm-6">
								<img src="http://res.cloudinary.com/dfg9corup/image/upload/v1494952691/girl1_msgqqi.jpg" class="girl img-responsive" alt="" />
								<img src="http://res.cloudinary.com/dfg9corup/image/upload/v1494952691/pricing_pqzmcg.png"  class="pricing" alt="" />
							</div>
						</div>
						<div class="item">
							<div class="col-sm-6">
								<h1><span>E</span>-SHOPPER</h1>
								<h2>100% Responsive Design</h2>
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
								<button type="button" class="btn btn-default get">Get it now</button>
							</div>
							<div class="col-sm-6">
								<img src="http://res.cloudinary.com/dfg9corup/image/upload/v1494952692/girl2_a0tvgn.jpg" class="girl img-responsive" alt="" />
								<img src="http://res.cloudinary.com/dfg9corup/image/upload/v1494952691/pricing_pqzmcg.png"  class="pricing" alt="" />
							</div>
						</div>

						<div class="item">
							<div class="col-sm-6">
								<h1><span>E</span>-SHOPPER</h1>
								<h2>Free Ecommerce Template</h2>
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
								<button type="button" class="btn btn-default get">Get it now</button>
							</div>
							<div class="col-sm-6">
								<img src="http://res.cloudinary.com/dfg9corup/image/upload/v1494952691/girl3_oy46s8.jpg" class="girl img-responsive" alt="" />
								<img src="http://res.cloudinary.com/dfg9corup/image/upload/v1494952691/pricing_pqzmcg.png" class="pricing" alt="" />
							</div>
						</div>
					</div>

					<a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
						<i class="fa fa-angle-left"></i>
					</a>
					<a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
						<i class="fa fa-angle-right"></i>
					</a>
				</div>
				
			</div>
		</div>
	</div>
</section><!--/slider-->

<section>
	<div class="container">
		<div class="row">
			<div class="col-sm-3">
				<div class="left-sidebar">
					<h2>Category</h2>
					<div class="panel-group category-products" id="accordian"><!--category-productsr-->
						<div class="panel panel-default">
							<% @categories.each do |category| %>
								<div class="panel-heading">
									<h4 class="panel-title"><%= link_to category.name, category_path(category.id) %></h4>
								</div>
							<% end %>
						</div>
					</div><!--/category-products-->

					<div class="shipping text-center"><!--shipping-->
						<img src="http://res.cloudinary.com/dfg9corup/image/upload/v1495447323/shipping_njpbu4.jpg" alt="" />
					</div><!--/shipping-->

				</div>
			</div>

			<div class="col-sm-9 padding-right">
				<div class="features_items"><!--features_items-->
					<h2 class="title text-center">Features Items</h2>
					<div id="features_items">
						<%= render :partial => "item_index" %>
					</div>
				</div><!--features_items-->			
			</div>
		</div>
	</div>
</section>
<script>
  $(document).ready(function(){
      (function() {
          "use strict";
          if (window.location && window.location.hash) {
              if (window.location.hash === '#_=_') {
                  window.location.hash = '';
                  history.pushState('', document.title, window.location.pathname); // nice and clean
              }
          }
      }());
  });
</script>

app/views/categories/show.html.erb
<section id="slider"><!--slider-->
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div id="slider-carousel" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
            <li data-target="#slider-carousel" data-slide-to="1"></li>
            <li data-target="#slider-carousel" data-slide-to="2"></li>
          </ol>
          
          <div class="carousel-inner">
            <div class="item active">
              <div class="col-sm-6">
                <h1><span>E</span>-SHOPPER</h1>
                <h2>Free E-Commerce Template</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                <button type="button" class="btn btn-default get">Get it now</button>
              </div>
              <div class="col-sm-6">
                <img src="http://res.cloudinary.com/dfg9corup/image/upload/v1494952691/girl1_msgqqi.jpg" class="girl img-responsive" alt="" />
                <img src="http://res.cloudinary.com/dfg9corup/image/upload/v1494952691/pricing_pqzmcg.png"  class="pricing" alt="" />
              </div>
            </div>
            <div class="item">
              <div class="col-sm-6">
                <h1><span>E</span>-SHOPPER</h1>
                <h2>100% Responsive Design</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                <button type="button" class="btn btn-default get">Get it now</button>
              </div>
              <div class="col-sm-6">
                <img src="http://res.cloudinary.com/dfg9corup/image/upload/v1494952692/girl2_a0tvgn.jpg" class="girl img-responsive" alt="" />
                <img src="http://res.cloudinary.com/dfg9corup/image/upload/v1494952691/pricing_pqzmcg.png"  class="pricing" alt="" />
              </div>
            </div>

            <div class="item">
              <div class="col-sm-6">
                <h1><span>E</span>-SHOPPER</h1>
                <h2>Free Ecommerce Template</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                <button type="button" class="btn btn-default get">Get it now</button>
              </div>
              <div class="col-sm-6">
                <img src="http://res.cloudinary.com/dfg9corup/image/upload/v1494952691/girl3_oy46s8.jpg" class="girl img-responsive" alt="" />
                <img src="http://res.cloudinary.com/dfg9corup/image/upload/v1494952691/pricing_pqzmcg.png" class="pricing" alt="" />
              </div>
            </div>
          </div>

          <a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
            <i class="fa fa-angle-left"></i>
          </a>
          <a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
            <i class="fa fa-angle-right"></i>
          </a>
        </div>
        
      </div>
    </div>
  </div>
</section><!--/slider-->

<section>
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <div class="left-sidebar">
          <h2>Category</h2>
          <div class="panel-group category-products" id="accordian"><!--category-productsr-->
            <div class="panel panel-default">
              <% @categories.each do |category| %>
                <div class="panel-heading">
                  <h4 class="panel-title"><%= link_to category.name, category_path(category.id) %></h4>
                </div>
              <% end %>
            </div>
          </div><!--/category-products-->

          <div class="shipping text-center"><!--shipping-->
            <img src="http://res.cloudinary.com/dfg9corup/image/upload/v1495447323/shipping_njpbu4.jpg" alt="" />
          </div><!--/shipping-->

        </div>
      </div>

      <div class="col-sm-9 padding-right">
        <div class="features_items"><!--features_items-->
          <h2 class="title text-center">Features Items</h2>
          <div id="features_items">
            <%= render :partial => "item_index" %>
          </div>
        </div><!--features_items-->     
      </div>
    </div>
  </div>
</section>

app/views/categories/show.js.erb
$('#features_items').html("<%= escape_javascript(render :partial => 'item_index') %>")
$('.pagination a').attr('data-remote', 'true')